name: Gatling Manual Run

on:
  workflow_dispatch:
    inputs:
      USERS:
        description: 'Number of ramp users'
        required: false
        default: '10'
      DURATION:
        description: 'Ramp duration in seconds'
        required: false
        default: '30'

jobs:
  gatling-test:
    runs-on: linux-qa

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Run Gatling simulation with dynamic ramp-up
        run: |
          sbt "gatling:testOnly DynamicRampUpSimulation -DUSERS=${{ github.event.inputs.USERS }} -DDURATION=${{ github.event.inputs.DURATION }}"