name: Selenium Automation

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '0 7 * * *' # Runs at 7:00 UTC every day (optional)

jobs:
  selenium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Or your preferred version

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run Selenium script
        run: python database_automation.py
        env:
          USERNAME: "Admin"
          PASSWORD: "rFt9f7YcvzZlI7kL"
